- name: Play nginx
  hosts: web_servers
  become: yes

  tasks:
    - name: Install reqs for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: yes

    - name: Install the Docker module for Python
      pip:
        name: docker

    - name: Create a directory /home/user/html if it does not exist
      ansible.builtin.file:
        path: /home/matiz/html
        state: directory
        mode: "0777"

    - name: Create a directory /var/www/html if it does not exist
      ansible.builtin.file:
        path: /var/wwww/html/
        state: directory
        mode: "0777"

    - name: Create a directory /var/log/nginx if it does not exist
      ansible.builtin.file:
        path: /var/log/nginx
        state: directory
        mode: "0777"

    - name: Copy index.html
      ansible.builtin.copy:
        src: /home/skopkin/sys-diplom/Ansible/index.html
        dest: /var/www/html/index.html
        mode: "0777"

    - name: Create container
      docker_container:
        name: "nginx"
        image: "nginx:latest"
        volumes:
          - /home/matiz/html:/usr/share/nginx/html
          - /var/log/nginx:/var/log/nginx

        ports:
          - "80:80"
        state: started
        restart_policy: always
